name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install dependencies
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: signal-apk
        path: app/build/outputs/apk/release/app-release.apk
